In [87]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor 
from sklearn import model_selection

In [88]:
df=pd.read_csv('datasets.csv', sep=',')

In [89]:
pd.set_option("display.max_rows", 20, "display.max_columns", None)
df.head() #позволяет увидеть максимальное количество столбцов (Sets the value of the specified option)

,SalePrice,YearBuilt,YrSold,MonthSold,Size(sqf),Floor,HallwayType,HeatingType,AptManageType,N_Parkinglot(Ground),N_Parkinglot(Basement),TimeToBusStop,TimeToSubway,N_APT,N_manager,N_elevators,SubwayStation,N_FacilitiesNearBy(PublicOffice),N_FacilitiesNearBy(Hospital),N_FacilitiesNearBy(Dpartmentstore),N_FacilitiesNearBy(Mall),N_FacilitiesNearBy(ETC),N_FacilitiesNearBy(Park),N_SchoolNearBy(Elementary),N_SchoolNearBy(Middle),N_SchoolNearBy(High),N_SchoolNearBy(University),N_FacilitiesInApt,N_FacilitiesNearBy(Total),N_SchoolNearBy(Total)
0,141592,2006,2007,8,814,3,terraced,individual_heating,management_in_trust,111.0,184.0,5min~10min,10min~15min,3.0,3.0,0.0,Kyungbuk_uni_hospital,2.0,1,1.0,1.0,1.0,0.0,3.0,2.0,2.0,2.0,5,6.0,9.0
1,51327,1985,2007,8,587,8,corridor,individual_heating,self_management,80.0,76.0,0~5min,5min~10min,1.0,2.0,2.0,Daegu,5.0,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,0.0,3,12.0,4.0
2,48672,1985,2007,8,587,6,corridor,individual_heating,self_management,80.0,76.0,0~5min,5min~10min,1.0,2.0,2.0,Daegu,5.0,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,0.0,3,12.0,4.0
3,380530,2006,2007,8,2056,8,terraced,individual_heating,management_in_trust,249.0,536.0,0~5min,0-5min,6.0,5.0,11.0,Sin-nam,1.0,1,0.0,1.0,0.0,0.0,2.0,2.0,1.0,2.0,5,3.0,7.0
4,221238,1993,2007,8,1761,3,mixed,individual_heating,management_in_trust,523.0,536.0,0~5min,15min~20min,8.0,8.0,20.0,Myung-duk,6.0,2,0.0,1.0,5.0,0.0,4.0,3.0,5.0,5.0,4,14.0,17.0

In [90]:
df = df_raw.copy()

In [91]:
# df['SubwayStation'].unique() - показывает уникальные значения в данной колонке

In [92]:
def time_to(line):
    if line =='no_bus_stop_nearby':
        return 1000
    minute = line.replace('min', '').replace('-', '~').split('~')
    minute = [int(num) for num in minute]
    return max(minute)

In [93]:
def dummies_for(df, col_name):
    dummies = pd.get_dummies(df[col_name])
    for column in dummies.columns:
        df[column] = dummies[column]
    df = df.drop([col_name], axis = 1)
    return df

In [94]:
df['HeatingType']=df['HeatingType'].map(lambda x: 1 if x == 'individual_heating' else 0)
df['AptManageType']=df['AptManageType'].map(lambda x: 1 if x =='AptManageType' else 0)
df['TimeToSubway']=df['TimeToSubway'].map(time_to)
df['TimeToBusStop']=df['TimeToBusStop'].map(time_to)
df = dummies_for(df, 'HallwayType')
df = dummies_for(df, 'SubwayStation')

In [123]:
df_raw

,SalePrice,YearBuilt,YrSold,MonthSold,Size(sqf),Floor,HallwayType,HeatingType,AptManageType,N_Parkinglot(Ground),N_Parkinglot(Basement),TimeToBusStop,TimeToSubway,N_APT,N_manager,N_elevators,SubwayStation,N_FacilitiesNearBy(PublicOffice),N_FacilitiesNearBy(Hospital),N_FacilitiesNearBy(Dpartmentstore),N_FacilitiesNearBy(Mall),N_FacilitiesNearBy(ETC),N_FacilitiesNearBy(Park),N_SchoolNearBy(Elementary),N_SchoolNearBy(Middle),N_SchoolNearBy(High),N_SchoolNearBy(University),N_FacilitiesInApt,N_FacilitiesNearBy(Total),N_SchoolNearBy(Total)
0,141592,2006,2007,8,814,3,terraced,individual_heating,management_in_trust,111.0,184.0,10,15,3.0,3.0,0.0,Kyungbuk_uni_hospital,2.0,1,1.0,1.0,1.0,0.0,3.0,2.0,2.0,2.0,5,6.0,9.0
1,51327,1985,2007,8,587,8,corridor,individual_heating,self_management,80.0,76.0,5,10,1.0,2.0,2.0,Daegu,5.0,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,0.0,3,12.0,4.0
2,48672,1985,2007,8,587,6,corridor,individual_heating,self_management,80.0,76.0,5,10,1.0,2.0,2.0,Daegu,5.0,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,0.0,3,12.0,4.0
3,380530,2006,2007,8,2056,8,terraced,individual_heating,management_in_trust,249.0,536.0,5,5,6.0,5.0,11.0,Sin-nam,1.0,1,0.0,1.0,0.0,0.0,2.0,2.0,1.0,2.0,5,3.0,7.0
4,221238,1993,2007,8,1761,3,mixed,individual_heating,management_in_trust,523.0,536.0,5,20,8.0,8.0,20.0,Myung-duk,6.0,2,0.0,1.0,5.0,0.0,4.0,3.0,5.0,5.0,4,14.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5886,511504,2007,2017,8,1643,19,terraced,individual_heating,management_in_trust,0.0,1270.0,5,5,7.0,14.0,16.0,Kyungbuk_uni_hospital,3.0,1,2.0,1.0,0.0,2.0,3.0,3.0,2.0,2.0,10,9.0,10.0
5887,298230,2006,2017,8,903,13,terraced,individual_heating,management_in_trust,123.0,181.0,10,5,3.0,3.0,11.0,Myung-duk,3.0,1,1.0,1.0,2.0,0.0,4.0,3.0,3.0,1.0,4,8.0,11.0
5888,357522,2007,2017,8,868,20,terraced,individual_heating,management_in_trust,0.0,1270.0,5,5,7.0,14.0,16.0,Kyungbuk_uni_hospital,3.0,1,2.0,1.0,0.0,2.0,3.0,3.0,2.0,2.0,10,9.0,10.0
5889,312389,1978,2017,8,1327,1,corridor,individual_heating,self_management,87.0,0.0,5,5,2.0,1.0,4.0,Kyungbuk_uni_hospital,3.0,2,1.0,1.0,0.0,0.0,3.0,3.0,3.0,2.0,3,7.0,11.0
5890,393805,2007,2017,8,868,13,terraced,individual_heating,management_in_trust,0.0,1270.0,5,5,7.0,14.0,16.0,Kyungbuk_uni_hospital,3.0,1,2.0,1.0,0.0,2.0,3.0,3.0,2.0,2.0,10,9.0,10.0

In [100]:
x = df.drop(['SalePrice'], axis =1)
y = df['SalePrice']

In [101]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.5)

In [102]:
modelka = DecisionTreeRegressor(max_depth=20)

In [103]:
modelka.fit(x_train, y_train)

DecisionTreeRegressor(max_depth=20)

In [104]:
pred = modelka.predict(x_test)

In [105]:
# deviation

In [106]:
kfold = model_selection.KFold(n_splits = 5, 
                       random_state = 8) 

model = BaggingRegressor(base_estimator = DecisionTreeRegressor(), 
                          n_estimators = 500, 
                          random_state = 10) 
  
results = model_selection.cross_val_score(model, x_test, y_test, cv = kfold) 
print("accuracy :") 
print(round(results.mean() * 100))

/home/nastya/venv/lib/python3.8/site-packages/sklearn/model_selection/_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(

accuracy :
98.0

In [107]:
model

BaggingRegressor(base_estimator=DecisionTreeRegressor(), n_estimators=500,
                 random_state=10)

In [108]:
kfold

KFold(n_splits=5, random_state=8, shuffle=False)

# SQL

In [109]:
import pymysql
import pymysql.cursors

In [111]:
df_raw.columns

Index(['SalePrice', 'YearBuilt', 'YrSold', 'MonthSold', 'Size(sqf)', 'Floor',
       'HallwayType', 'HeatingType', 'AptManageType', 'N_Parkinglot(Ground)',
       'N_Parkinglot(Basement)', 'TimeToBusStop', 'TimeToSubway', 'N_APT',
       'N_manager', 'N_elevators', 'SubwayStation',
       'N_FacilitiesNearBy(PublicOffice)', 'N_FacilitiesNearBy(Hospital)',
       'N_FacilitiesNearBy(Dpartmentstore)', 'N_FacilitiesNearBy(Mall)',
       'N_FacilitiesNearBy(ETC)', 'N_FacilitiesNearBy(Park)',
       'N_SchoolNearBy(Elementary)', 'N_SchoolNearBy(Middle)',
       'N_SchoolNearBy(High)', 'N_SchoolNearBy(University)',
       'N_FacilitiesInApt', 'N_FacilitiesNearBy(Total)',
       'N_SchoolNearBy(Total)'],
      dtype='object')

In [113]:
conn = pymysql.connect(host = 'localhost',
                             user = 'nastya',
                             db='lil_db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

In [115]:
df_raw['TimeToSubway']=df_raw['TimeToSubway'].map(time_to)
df_raw['TimeToBusStop']=df_raw['TimeToBusStop'].map(time_to)

In [124]:
df_raw['YearBuilt'].dtype
#.dtype - узнать тип колонки

dtype('int64')

In [150]:
column_type = ""
for column in df_raw.columns:
    python_type = df_raw[column].dtype.name
    sql_type = 'int'
    if python_type == 'float64':
        sql_type = 'float'
    elif python_type == 'object':
        sql_type = 'varchar(200)'
    column_type += column.replace(" ", "_").replace('(', "").replace(')', '')+ " " + sql_type+ ","
column_type = column_type[:-1]
column_type

'SalePrice int,YearBuilt int,YrSold int,MonthSold int,Sizesqf int,Floor int,HallwayType varchar(200),HeatingType varchar(200),AptManageType varchar(200),N_ParkinglotGround float,N_ParkinglotBasement float,TimeToBusStop int,TimeToSubway int,N_APT float,N_manager float,N_elevators float,SubwayStation varchar(200),N_FacilitiesNearByPublicOffice float,N_FacilitiesNearByHospital int,N_FacilitiesNearByDpartmentstore float,N_FacilitiesNearByMall float,N_FacilitiesNearByETC float,N_FacilitiesNearByPark float,N_SchoolNearByElementary float,N_SchoolNearByMiddle float,N_SchoolNearByHigh float,N_SchoolNearByUniversity float,N_FacilitiesInApt int,N_FacilitiesNearByTotal float,N_SchoolNearByTotal float'

In [141]:
with conn.cursor() as cursor:
    cursor.execute("drop table if exists kvartira")

In [142]:
!whoami

nastya

In [144]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://nastya@localhost/lil_db')

In [147]:
engine.table_names() 
#показывает какие есть таблицфы в базе

['locations', 'runner', 'runs', 'titanic']

In [153]:
with conn.cursor() as cursor:
    cursor.execute('create table kvartira (id serial primary key, %s)' % column_type)

In [167]:
with conn.cursor() as cursor:
    cursor.execute("SELECT * FROM kvartira")
    print(cursor.fetchall())

()

In [164]:
df_raw.rename(columns=lambda old: old.replace(" ", "_").replace("(", "").replace(')', ''), inplace=True)
df_raw

,SalePrice,YearBuilt,YrSold,MonthSold,Sizesqf,Floor,HallwayType,HeatingType,AptManageType,N_ParkinglotGround,N_ParkinglotBasement,TimeToBusStop,TimeToSubway,N_APT,N_manager,N_elevators,SubwayStation,N_FacilitiesNearByPublicOffice,N_FacilitiesNearByHospital,N_FacilitiesNearByDpartmentstore,N_FacilitiesNearByMall,N_FacilitiesNearByETC,N_FacilitiesNearByPark,N_SchoolNearByElementary,N_SchoolNearByMiddle,N_SchoolNearByHigh,N_SchoolNearByUniversity,N_FacilitiesInApt,N_FacilitiesNearByTotal,N_SchoolNearByTotal
0,141592,2006,2007,8,814,3,terraced,individual_heating,management_in_trust,111.0,184.0,10,15,3.0,3.0,0.0,Kyungbuk_uni_hospital,2.0,1,1.0,1.0,1.0,0.0,3.0,2.0,2.0,2.0,5,6.0,9.0
1,51327,1985,2007,8,587,8,corridor,individual_heating,self_management,80.0,76.0,5,10,1.0,2.0,2.0,Daegu,5.0,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,0.0,3,12.0,4.0
2,48672,1985,2007,8,587,6,corridor,individual_heating,self_management,80.0,76.0,5,10,1.0,2.0,2.0,Daegu,5.0,1,2.0,1.0,2.0,1.0,2.0,1.0,1.0,0.0,3,12.0,4.0
3,380530,2006,2007,8,2056,8,terraced,individual_heating,management_in_trust,249.0,536.0,5,5,6.0,5.0,11.0,Sin-nam,1.0,1,0.0,1.0,0.0,0.0,2.0,2.0,1.0,2.0,5,3.0,7.0
4,221238,1993,2007,8,1761,3,mixed,individual_heating,management_in_trust,523.0,536.0,5,20,8.0,8.0,20.0,Myung-duk,6.0,2,0.0,1.0,5.0,0.0,4.0,3.0,5.0,5.0,4,14.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5886,511504,2007,2017,8,1643,19,terraced,individual_heating,management_in_trust,0.0,1270.0,5,5,7.0,14.0,16.0,Kyungbuk_uni_hospital,3.0,1,2.0,1.0,0.0,2.0,3.0,3.0,2.0,2.0,10,9.0,10.0
5887,298230,2006,2017,8,903,13,terraced,individual_heating,management_in_trust,123.0,181.0,10,5,3.0,3.0,11.0,Myung-duk,3.0,1,1.0,1.0,2.0,0.0,4.0,3.0,3.0,1.0,4,8.0,11.0
5888,357522,2007,2017,8,868,20,terraced,individual_heating,management_in_trust,0.0,1270.0,5,5,7.0,14.0,16.0,Kyungbuk_uni_hospital,3.0,1,2.0,1.0,0.0,2.0,3.0,3.0,2.0,2.0,10,9.0,10.0
5889,312389,1978,2017,8,1327,1,corridor,individual_heating,self_management,87.0,0.0,5,5,2.0,1.0,4.0,Kyungbuk_uni_hospital,3.0,2,1.0,1.0,0.0,0.0,3.0,3.0,3.0,2.0,3,7.0,11.0
5890,393805,2007,2017,8,868,13,terraced,individual_heating,management_in_trust,0.0,1270.0,5,5,7.0,14.0,16.0,Kyungbuk_uni_hospital,3.0,1,2.0,1.0,0.0,2.0,3.0,3.0,2.0,2.0,10,9.0,10.0

In [165]:
df_raw.to_sql(name='kvartira', con=engine, if_exists = 'append', index=False)